# Generated by Django 5.0.7 on 2024-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='developer_project',
            field=models.ManyToManyField(related_name='developer_project', through='project.DevelopedBy', to='project.project'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='qa_project',
            field=models.ManyToManyField(related_name='qa_project', through='project.AssuredBy', to='project.project'),
        ),
    ]
