# Generated by Django 5.1 on 2024-08-08 20:39

import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('deadline', models.DateField()),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('screenshot', models.ImageField(upload_to='static/media/', validators=[task.models.validate_image_format])),
                ('developer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_id', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='project.project')),
                ('qa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
